var backupStories = [
  {
    "id": 1386,
    "title": 0,
    "soc": 7130,
    "region": "east",
    "salary": 10230.7,
    "is_female": 1,
    "part_time": 1,
    "city": "Ely",
    "job": "service centre supervisor",
    "other_country": "Nigeria",
    "gender": "female",
    "partner_title": "husband",
    "partner_pronoun": "he"
  },
  {
    "id": 233,
    "title": 0,
    "soc": 4159,
    "region": "east midlands",
    "salary": 15114.9,
    "is_female": 0,
    "part_time": false,
    "city": "Nottingham",
    "job": "clerical worker",
    "other_country": "China",
    "gender": "male",
    "partner_title": "wife",
    "partner_pronoun": "she"
  },
  {
    "id": 228,
    "title": 0,
    "soc": 8111,
    "region": "yorkshire and the humber",
    "salary": 16075.9,
    "is_female": 0,
    "part_time": false,
    "city": "Hereford",
    "job": "bakery assistant",
    "other_country": "Uruguay",
    "gender": "male",
    "partner_title": "wife",
    "partner_pronoun": "she"
  },
  {
    "id": 177,
    "title": 0,
    "soc": 9232,
    "region": "west midlands",
    "salary": 16707,
    "is_female": 0,
    "part_time": false,
    "city": "Lichfield",
    "job": "road maintenence worker",
    "other_country": "the United States",
    "gender": "male",
    "partner_title": "wife",
    "partner_pronoun": "she"
  },
  {
    "id": 439,
    "title": 0,
    "soc": 5435,
    "region": "east midlands",
    "salary": 8040.63,
    "is_female": 1,
    "part_time": false,
    "city": "Leicester",
    "job": "fish fryer",
    "other_country": "Turkey",
    "gender": "female",
    "partner_title": "husband",
    "partner_pronoun": "he"
  },
  {
    "id": 249,
    "title": 0,
    "soc": 6232,
    "region": "wales",
    "salary": 17525,
    "is_female": 0,
    "part_time": false,
    "city": "St Asaph",
    "job": "mosque attendant",
    "other_country": "Iran",
    "gender": "male",
    "partner_title": "wife",
    "partner_pronoun": "she"
  },
  {
    "id": 1133,
    "title": 0,
    "soc": 6240,
    "region": "scotland",
    "salary": 6221,
    "is_female": 1,
    "part_time": 1,
    "city": "Glasgow",
    "job": "house cleaner",
    "other_country": "Uruguay",
    "gender": "female",
    "partner_title": "husband",
    "partner_pronoun": "he"
  }
]
